### ISSUE TITLE
Use Guzzle

### ISSUE THREAD

**Issue by jbrooksuk** [DivineOmega/cachet.php#7]
You're duplicating a lot of code for cURL.

**Comment by Jord-JD** [comment]
Great idea. Guzzle looks pretty good.

**Comment by Jord-JD** [comment]
Basic Guzzle integration for getting of components, incidents and metric.

TODO: Change setting to use Guzzle (PUT request).

**Comment by Jord-JD** [comment]
Done. :smile:
